doctrine:
  dbal:
    url: 'sqlite:///%kernel.project_dir%/var/searching.db'
  orm:
    auto_mapping: false
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    mappings:
      Searching:
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Searching\Entity'
        alias: Searching
        is_bundle: false
